.gitmodules, netlify.toml, site/.gitignore, site/Makefile, site/archetypes/default.md, site/config.toml, site/content/en/_index.html, site/content/en/community/_index.md, site/content/en/docs/Contribution guidelines/_index.md, site/content/en/docs/Overview/_index.md, site/content/en/docs/_index.md, site/package-lock.json, site/package.json
The reason why there are so many commits is because I merged in the Docsy (Hugo) theme's starter website (the recommended way to install/use the theme). The merge made it easier to bring over the submodules that come with the Docsy theme.
I went ahead and removed some of the built-in docs pages (see the commits near HEAD), and did a rough s/docsy/prow replacement to make the site make more sense. It also includes the `netlify.toml` from https://github.com/kubernetes/test-infra/pull/25042 with a minor tweak in the domain name.
=> Bring in basic (mostly empty), fully-themed site

netlify.toml, site/Makefile
The "site" folder does not need to specified again for the "publish"
field because it is relative to the "base" field, as per the docs [1]:
[build]
base = "project/"
publish = "build-output/"
[1]: https://docs.netlify.com/configure-builds/file-based-configuration/
=> fix netlify preview

site/content/en/_index.html
This center-aligns the "Contributions welcome!" bit near the footer of the main landing page.
=> center-align block on main page

netlify.toml
Netlify by default prevents builds where it detects that there are no
changes. This appears to be simply broken. In the case of this PR#7 [1],
we observed a successful preview at [2], and yet the deployment failed
with a
10:35:30 AM: No changes detected in base directory. Returning early from build.
message [3], preventing the docs site from being updated.
The change here adds a workaround [4] to always make the "ignore build"
optimization fail with the "false" command. This is OK because this site
is a pure documentation site, so there is no real danger of building
when we don't need to (as is the case for repos that have docs colocated
with their source code).
[1]: https://github.com/kubernetes-sigs/prow/pull/7
[2]: https://deploy-preview-7--k8s-prow.netlify.app/
[3]: …
=> disable build skip optimization

.gitmodules, site/.rgignore, site/Makefile, site/config.toml, site/go.mod, site/go.sum
The dependencies are now tracked via go.mod and go.sum. The guide at https://www.docsy.dev/docs/updating/convert-site-to-module/ was used for this migration.
=> migrate to hugo modules

site/content/en/docs/_index.md
This information is out-of-date and gives a false sense of incompleteness.
/cc @cjwagner @jihoon-seo
=> remove migration notice

site/content/en/docs/components/cli-tools/tackle.md, site/content/en/docs/components/undocumented/tackle.md, site/content/en/docs/getting-started-deploy.md
- Supersedes & closes #24
(which is a translation of https://github.com/kubernetes/test-infra/pull/26754)
- We have 2 options here for this PR:
- We might cherrypick the first commit ('Remove Tackle from Prow Deployment guide') only,
since the `tackle` tool is not actively maintained and thus not really supported.
- Or, although the tool is not actively maintained and thus not really supported,
we might preserve the doc for `tackle`.
(If we choose this option, then it would be good to change the PR title, as it will become the commit message of squashed commit on `main` branch.)
FYI:
From my experience of deploying Prow 1) using tackle, and 2) manually,
- the Prow depolyment guide instructs to create and configure GitHub App,
`tackle` created a webhook to my GitHub org, instead of …
=> Remove Tackle from Prow Deployment guide

site/config.toml
Later we can upgrade to Google-indexed search, as outlined here: https://www.docsy.dev/docs/adding-content/navigation/#setting-up-site-search
Temporarily addresses #34
/cc @jihoon-seo @cjwagner
=> add search in sidebar

site/content/en/docs/getting-started-deploy.md
The deploy instructions seem to miss the step where you put in the webhook secret in the GitHub App config.  It wasn't super hard to figure out what was the issue but having it here will make life easier for people.
=> Add step to fill in webhook secret

site/content/en/docs/announcements.md
Reference: https://github.com/kubernetes/test-infra/pull/28393
=> announcement: remove k8s-ci-robot's at-mention from some instances

site/content/en/docs/spyglass/_index.md
I didn't realize it was possible to setup `gcs_browser_prefix` for S3, but I found a way to do it and thought it would be nice to share that with others in the documentation.
=> Add example value for gcs_browser_prefix for AWS S3

site/content/en/docs/announcements.md
Reverts kubernetes-sigs/prow#54
The blobless fetches were reverted for now due to unforeseen merge issues.
=> Revert "Update announcements.md for blobless cloning"

site/content/en/docs/overview/_index.md
I am a maintainer of Prow instance for TiDB and a member of [pingcap](https://github.com/pingcap) ORG.
> TiDB is a product of [PingCAP](https://www.pingcap.com).
The instance was migrated to new domain prow.tidb.net for one year. Now the old domain(prow.tidb.io) is offline.
=> Update prow instance url for TiDB

site/content/en/docs/getting-started-deploy.md
If using `branchprotector` with the GitHub App, one needs to add read and write permissions for repo administration.
ref https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-administration
=> Update permissions list for branch protection

site/content/en/docs/components/optional/gangway.md
This adds some basic docs about Gangway, bringing together the various reference materials that already exist in k/t-i.
/cc @cjwagner @airbornepony @timwangmusic
=> add gangway docs

hack/scripts/sync-prow.sh
Add a script to sync Prow commits from test-infra repo to the current repo. The script is based on this [comment](https://github.com/kubernetes-sigs/prow/pull/74#issuecomment-1907347751) from @listx with modifications.
Running the script assumes installation of `git` and `git-filter-repo` tools.
=> Add script to sync Prow commits from test-infra repo

hack/build/ensure-node_modules.sh, hack/run-in-node-container.sh, hack/ts.rollup_bundle.min.minify_options.json, package.json, rollup.config.js, tsconfig.json
The configs in top level folder and hack/ are hidden dependencies for gather-static.sh (in prow/cmd/deck, which is called by prowimagebuilder) and ts_rollup.
Tested prow/cmd/deck can be successfully built with these changes.
=> Add missing build dependencies from test-infra for deck image build

hack/scripts/.gitignore, hack/scripts/sync-prow.sh
/assign @listx @simony-gke 
I used this script to generate this branch: https://github.com/cjwagner/prow/tree/sync
The branch will not merge cleanly so we'll need to refresh the sync and force push this to the main branch when we're ready. I don't think subsequent syncs will require a force push, but I am not certain.
=> Fix sync-prow.sh to avoid duplicating commit history.

README.md
This should trigger the image publishing postsubmit added in https://github.com/kubernetes/test-infra/pull/32417
If this works we can start removing Prow related things from kubernetes/test-infra
=> Update README to reflect the source code migration.

prow/cmd/generic-autobumper/main.go
When there is an image consistency error, it would be helpful to know where the conflict came from.
For example, this error was difficult to debug: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-autobump-prow/1777837897014054912
> ```
> time="2024-04-09T23:16:30Z" level=fatal msg="failed to run the bumper tool" error="process function 0: gcr.io/k8s-prow/commenter:v20240405-c76de01869:v20240409-13cd3acf7e not bumped consistently for prefix gcr.io/k8s-prow/(Prow), expected version: v20240409-0bca2f141"
> ```
/assign @michelle192837
=> Make image consistency errors more actionable.

pkg/flagutil/kubernetes_cluster_clients.go
Similar to this error: https://github.com/kubernetes-sigs/prow/compare/main...inteon:prow:error_include_clustername?expand=1#diff-7d688313b319388bc790c0799da5081d6648feaeaf7945b26e5b6a93752b044dR389, include the cluster name in the error message.
Currently the error message looks like this:
```json
{
"component":"prow-controller-manager",
"error":"failed pod resource authorization check: [missing permissions: unable to \"create\" pods, missing permissions: unable to \"delete\" pods, missing permissions: unable to \"list\" pods, missing permissions: unable to \"watch\" pods, missing permissions: unable to \"get\" pods, missing permissions: unable to \"patch\" pods]",
"file":"sigs.k8s.io/prow/prow/cmd/prow-controller-manager/main.go:170",
"func":"main.main",
"level":"error",
"msg":"Failed …
```
=> Include cluster name in authorization error messages

site/content/en/docs/build-test-update.md, site/content/en/docs/components/cli-tools/generic-autobumper.md, site/content/en/docs/components/cli-tools/peribolos.md, site/content/en/docs/components/cli-tools/phaino.md, site/content/en/docs/components/cli-tools/phony.md, site/content/en/docs/components/core/deck/_index.md, site/content/en/docs/components/core/prow-controller-manager.md, site/content/en/docs/components/deprecated/cm2kc.md, site/content/en/docs/components/deprecated/plank.md, site/content/en/docs/components/optional/branchprotector.md, site/content/en/docs/components/optional/hmac.md, site/content/en/docs/components/optional/tot/fallbackcheck.md, site/content/en/docs/getting-started-deploy.md, site/content/en/docs/spyglass/write-a-lens.md, site/content/en/docs/test/integration/_index.md
The PR #101 has moved `cmd`, `pkg`, & `test` directories which was in `prow/`, to the root of the repo.
This PR is a follow-up of #101, updating `cmd`, `pkg`, & `test` paths in docs.
Note: Outdated URLs will be updated in other PR (#103).
=> doc: Update `cmd`, `pkg`, & `test` paths (follow-up of #101)

pkg/tide/tide.go
The GitHub API seems to have changed the conclusion to now return `skipped`. Tide should consider this status as success to be able to merge the PR.
Fixes https://github.com/kubernetes-sigs/prow/issues/130
=> tide: consider `skipped` run conclusion as `success`

cmd/peribolos/main.go
Having the caller on the info level makes it impossible to disable the extra context information. That's unfortunate because as a user of Peribolos the additional `func` and `file` fields make the log harder to read than necessary.
I think a good compromise would be to only include the caller info on the debug level.
=> [peribolos] only log caller when log level is raised

.golangci.yml, cmd/sinker/main_test.go, pkg/crier/controller_test.go, pkg/crier/reporters/gerrit/reporter_test.go, pkg/crier/reporters/github/reporter_test.go, pkg/deck/jobs/jobs_test.go, pkg/pjutil/abort_test.go, pkg/plank/controller_test.go, pkg/plank/reconciler_test.go, pkg/tide/gerrit_test.go, pkg/tide/status_test.go, pkg/tide/tide_test.go
This performs some cleanup and replaces the deprecated usage of NewFakeClient() with the new NewClientBuilder() API.
=> replace deprecated NewFakeClient with NewClientBuilder

pkg/github/client.go, pkg/github/client_test.go
This removes all deprecated functions in the GitHub client that are already unused. Some, like ListTeamMembers, are still required for deprecated configuration options, which I did not want to touch in this PR.
=> Remove deprecated GitHub client functions

cmd/external-plugins/cherrypicker/lib/lib.go, cmd/external-plugins/cherrypicker/server.go, cmd/external-plugins/cherrypicker/server_test.go, pkg/plugins/bugzilla/bugzilla_test.go
This PR adds support for listing multiple branches to cherrypick to in a single line. When multiple branches are detected, a cherrypick is created for the first listed branch and the cherrypick will contain a `/cherrypick` command for the remaining branches. This allows a user to specify a chain of cherrypicks, where the first listed branch must be merged before moving onto the next.
=> external-plugins/cherrypicker: add support for branch chains

.gitignore
This PR organizes `.gitignore` file, where the details are:
- adds some heading comments
- adds Golang-related entities
(from https://github.com/github/gitignore/blob/main/Go.gitignore)
- adds Hugo-related entities
(from https://github.com/github/gitignore/blob/main/community/Golang/Hugo.gitignore)
/label tide/merge-method-squash
=> Organize `.gitignore`

README.md, cloudbuild.yaml
Part of https://github.com/kubernetes-sigs/prow/issues/113 
Part of https://github.com/kubernetes/k8s.io/pull/6740
Right now, our postsubmit job [runs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-push-prow/1781305980542259200) in a pod which breaks our trusted cluster build policies.
I tested this build at https://console.cloud.google.com/cloud-build/builds;region=global/ce637e5c-b605-490f-b104-589b7dca23c6?project=k8s-infra-ii-sandbox
@BenTheElder @ameukam
=> build images using cloudbuild

pkg/plugins/assign/assign.go, pkg/plugins/assign/assign_test.go
close #145 
Support `/cc <teams>` `/assign <teams>` command to request review(s) to teams,
**Example**
For example, let’s assume that the members of the `kubernetes/sig-team-foo` team are Alice, Bob, and Carol.
In this case, `/cc kubernetes/sig-team-foo` command will request reviews from all three members: Alice, Bob, and Carol.
Of course,  `/assign` command works in the same way.
=> [Feature]: [assign plugin] Support GitHub Organization Teams as targets for assign/cc commands

pkg/plugins/OWNERS
Expand the contribex TL alias to get pinged on plugin changes ([ref](http://git.k8s.io/community/sig-contributor-experience/charter.md#cross-cutting-and-externally-facing-processes)). This way we also avoid creating an OWNERS_ALIAS file. I could not find the use of any other aliases in the existing OWNERS files.
/cc @Priyankasaggu11929 @cblecker 
/sig contributor-experience
=> plugins/OWNERS: expand contribex TL alias

cmd/external-plugins/cherrypicker/server.go, cmd/external-plugins/cherrypicker/server_test.go
This PR prepends the PR description to the comments list, allowing users to specify branches that they wish to cherrypick to when they first create the PR.
This change fixes the cherrypick chain functionality introduced in #136.
=> external-plugins/cherrypicker: include PR description as comment

cmd/prow-controller-manager/main.go, cmd/sinker/main.go, pkg/flagutil/kubernetes_cluster_clients.go, pkg/plank/reconciler.go, pkg/plank/reconciler_test.go
At the time controller-runtime was introduced to this project, it didn't have a clean abstraction for "cache + client of a cluster". The only thing it had was the manager, which is that plus some additional things like metrics, webhooks, leader election and code related to run things. As a result, we ended up using the manager and disabling everything it doesn't need.
By now, controller-runtime has the `cluster` abstraction for precisely this use-case. This change makes us use the `cluster` where appropriate. It should not result in any outwards-visible behavior changing.
=> Use Cluster and not Manager for build clusters

cmd/branchprotector/protect.go
Terminate branchprotector on TERM/INT signals. Otherwise we will leave threads running in the background or simply ignore the signals. For example, aborting a dry-run when testing it manually goes horribly wrong without this.
Fixes: #118
=> branchprotector: add support for SIGTERM/SIGINT catching

.ko.yaml
Bump git-custom-k8s-auth as a follow-up of:
- https://github.com/kubernetes/test-infra/pull/32940
This should help onboard Azure KS clusters on prow control plane.
=> Bump git-custom-k8s-auth image

.ko.yaml
Switch the image bases to use those built in k8s-staging-test-infra instead. Ref https://github.com/kubernetes/test-infra/issues/32432.
Atm: Just doing this for the `alpine` and `git-custom-k8s-auth` images.
=> Use k8s-staging-test-infra images for base images.

cmd/deck/OWNERS, cmd/generic-autobumper/OWNERS, pkg/deck/OWNERS, pkg/genyaml/OWNERS, pkg/spyglass/OWNERS
Cleaning up OWNERS files of devs who were previously on the Googler test-infra oncall rotation, but are no longer actively developing.
=> Move Travis and Mitchel to emeritus.

Makefile
The default is `prow/.prow-images.yaml`, which made sense when Prow was in k8s/test-infra since it was nested in a subdirectory, but doesn't make sense anymore now that the files are unnested in their own repo. We could update the default instead, but I think having the argument here explicitly is clearer in this crops up again in future.
I believe this should fix the image push job for Prow images (`post-k8s-infra-prow-images`), which doesn't have any published images in k8s-staging-test-infra yet.
Ref https://github.com/kubernetes/test-infra/issues/32432
=> Specify the image file for image build/push.

pkg/gerrit/client/client.go, pkg/gerrit/client/client_test.go
The old code assumed that when `err != nil`, the `resp` is still populated, which isn't true in all branches. This causes a panic which can occur every 6 hours
We add a `resp != nil` check to protect against this panic.
Also, add a unit test and fake gerritChange with errors which would catch this panic. I confirmed that removing the change triggers the test failure.
=> Fix panic in gerrit client ChangeExist

pkg/plugins/cherrypickapproved/cherrypickapproved.go, pkg/plugins/cherrypickapproved/cherrypickapproved_test.go, pkg/plugins/config.go
This PR extends the `cherrypickapproved` plugin with two new configuration options: `allow_missing_approved_label` and `allow_missing_lgtm_label`. Those two fields are bools defaulted to `false`. If the option is set to `true`, the respective label will not be needed to successfully cherry-pick approve the PR.
This is very useful for projects where approvers are also cherry-pick-approvers. At the moment, this plugin is not much useful to those projects, because you either have to approve the PR two times or manually remove the cherry-pick-not-approved label. This change should make the user experience a bit better for this use case.
/assign @saschagrunert @cpanato @puerco 
cc @kubernetes-sigs/release-engineering
=> cherrypickapproved: Add option to approve PRs without lgtm or approved labels

pkg/jira/fakejira/fake.go
Jira uses the project key to construct the issue key.
=> fakejira: use key instead of name for issue creation

pkg/config/prow-config-documented.yaml, pkg/config/scheduler.go, pkg/plugins/plugin-config-documented.yaml, pkg/scheduler/strategy/default.go, pkg/scheduler/strategy/external.go, pkg/scheduler/strategy/external_test.go
`External` sends `Job` field from prowjob spec to URL and expects cluster assignment in return
=> New scheduling strategy: external

netlify.toml
This PR is related with the issue #151.
This PR updates `netlify.toml` so that the Netlify build proceeds only if there are changes within the `site/` directory.
=> config: Enable Netlify build for `site/` directory only

pkg/scheduler/reconciler.go, pkg/scheduler/reconciler_test.go, pkg/scheduler/strategy/default.go, pkg/scheduler/strategy/external.go, pkg/scheduler/strategy/external_test.go
Fallback to cluster configured in the config file when unsuccessfull with scheduling for external strategy
=> Fallback to config in external strategy

site/content/en/docs/components/_index.md, site/content/en/docs/components/undocumented/grandmatriarch.md, site/content/en/docs/gerrit.md
The PR #218 has deleted `grandmatriach` codes from source base.
This PR deprecates `grandmatriach`-related docs accordingly.
=> docs: Deprecate `grandmatriarch` docs

pkg/github/client.go
We want to rerun workflows that we're triggered by `workflow_call` with Prow's `/retest` keyword, when `trigger_github_workflows: true` is enabled in plugin config.
Fixes: #276
=> add workflow_call triggered workflows to failed workflow search

pkg/ghcache/coalesce_test.go, pkg/ghcache/ghcache.go, pkg/github/ghmetrics/ghpath.go, pkg/simplifypath/simplify.go
This PR fixes 2 things:
- cache mode determination in coalesce.go (https://github.com/kubernetes-sigs/prow/blob/main/pkg/ghcache/coalesce.go#L242)
- add additional paths for repository API calls that we use and triggered a warning in ghproxy and asks to raise an issue with the project
in coalescer RoundTrip method, the cache Mode is determined at the end by inspecting the final response object. However, at this point the response object is not the original 304 response from the GitHub server anymore, but the cache response which has usually a status code of 200. So the method `cacheResponseMode` never returns `ModeRevalidated` but `Changed` which is also reflected in the cache.
This does not seem to have another negative effect afaict apart from being confusing and triggered me to inspect …
=> Fix cache mode determination

pkg/github/client.go, pkg/github/client_test.go, pkg/plugins/override/override.go, pkg/plugins/override/override_test.go
`OpenShift` CI needs to be able to update `CheckRuns` utilizing the GH client. These changes help to facilitate that.
=> `github client`: add function for updating a CheckRun, and return ID when creating one

.ko.yaml
This PR updates `gcr.io/k8s-prow/git:v20240129-a0a4e743bf` base images to `gcr.io/k8s-prow/git:v20240729-4f255edb07` which is the latest version.
The current version include [CVE-2024-6387](https://security.alpinelinux.org/vuln/CVE-2024-6387). While sshd is not started in the context, it still triggers security incidents in our scanners.
=> Update `gcr.io/k8s-prow/git` base image

pkg/config/prow-config-documented.yaml, pkg/config/tide.go, pkg/config/tide_test.go
OpenShift is developing a new external prow plugin that will create GitHub `check_runs`. These will have a consistent naming scheme, and we would like `tide` to ignore them. This new field will allow for this.
=> `tide`: allow for optional contexts to be defined via regex

cmd/deck/main.go, test/integration/config/prow/cluster/deck_tenant_deployment.yaml
Reverts kubernetes-sigs/prow#308
https://github.com/kubernetes-sigs/prow/pull/308#issuecomment-2457656048
> Stephen Goeddel
>  3 minutes ago
> New deck never becomes ready. I am going to try some additional logging with a locally built version, but will most likely reverting the bump (and the PR)
=> Revert "`deck`: don't serve the ready endpoint until immediately prior to starting the server"

go.mod, pkg/io/providers/aws.go, pkg/io/providers/aws_test.go
Commit https://github.com/kubernetes-sigs/prow/commit/77dc7b725f136fed43a3c01e90a70d3f89ae92f2 introduced breaking changes for users of prow that don't use AWS S3 since the endpoint field is not respected anymore.
This PR ensures that custom endpoints for S3 storage is respected as well as the insecure field.
=> fix: respect s3 custom endpoint config in aws sdk

hack/tools/ensure-kind.sh, test/integration/integration-test.sh
this is pretty cheap/fast, kind is a very small go binary, and upgrades can now be tested with PRs to this repo
fixes https://github.com/kubernetes-sigs/prow/issues/334
=> install kind for integration tests

pkg/github/types.go
GitHub no longer allows branch-protection to be set via the API on private repos using the free plan, we need to know the plan type to apply customized logic for some automation we have.
The `plan` property is described on https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#get-an-organization
=> Added a plan struct inside organization

pkg/io/providers/aws.go, pkg/io/providers/providers.go
At the moment we don't allow passing in an aws session token for the s3 provider... temporary tokens require that the session token also be provided with the access and secret keys. Without this change we don't allow temporary s3 tokens (tokens that start with `ASIA` instead of `AKIA`.
=> Allow Passing AWS Session Token

site/content/en/docs/getting-started-deploy.md
MinIO gateway was deprecated in 2022 and the functionality is no longer available in `minio/minio:latest` images.
This PR updates docs for deploying PROW on Azure to bring attention to this and also references the LKG container image that still containers this functionality.
Deprecation notice - https://blog.min.io/deprecation-of-the-minio-gateway/
Last known release docs - https://github.com/minio/minio/blob/RELEASE.2022-04-29T01-27-09Z/docs/gateway/azure.md
=> MinIO for Azure deprecation deployment warning + pinning LKG release

pkg/plugins/approve/approve_test.go, pkg/plugins/approve/approvers/approvers_test.go, pkg/plugins/approve/approvers/owners.go
Prow is used for other projects and we have a config item to change the code review process link... let's make the title a bit more generic to support more projects?
=> Genericize Code Review Link Title

cmd/deck/static/style.css
Currently, the command-help page renders multiline command examples (the
only example I've seen is for /release-note-edit) on one line, which is
confusing for users.
Change the style to respect newline in the source.
Link: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
Before: 
After:
=> Respect newline in command examples in command-help

OWNERS
Thanks y'all for previous contributions! Moving less active folks to emeritus to clean up the approvers list.
Follow-up to https://github.com/kubernetes-sigs/prow/pull/336.
=> Move some approvers to emeritus.

pkg/jenkins/controller.go, pkg/jenkins/controller_test.go, pkg/jenkins/jenkins.go
This can improved Jenkins type CI status display for better user experience.
- Keep the prow job as `triggered` when the Jenkins build is still in queue.
- Only set the prow job to `pending` state when the Jenkins build is running.
When a CI job was triggered, the status would show "Pending - Jenkins job enqueued" for running jobs, which could be misleading as it suggested the job hadn't started yet, and there are no links to view during the run.
Running CI jobs now display "Pending - Jenkins job running" with detail url provided.
=> refactor(pkg/jenkins): change the state update logic

cmd/checkconfig/testdata/combined.yaml, cmd/deck/template/spyglass.html, pkg/spyglass/lenses/buildlog/lens.go, pkg/spyglass/lenses/buildlog/lens_test.go
This provides the ability to configure iframe sandbox permissions pr lense. This allows the operator of the prow installation to define which permissions it trust to each lense.
PR comes from the ideas and discussions in
https://github.com/kubernetes-sigs/prow/pull/294
=> (spyglass/lenses) allow configuration sandbox permissions

cmd/horologium/main.go, cmd/horologium/main_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/jobs.go, pkg/kube/prowjob.go
This PR introduces a new configuration field (along with the functionality in horologium component) for ProwJobs to support automatically re-triggering periodic jobs based on a specified policy. The new `retrigger-failed-run` field allows retrying a failed periodic job with customizable settings for the number of attempts and the interval between retries.
Example usage:
```
retrigger-failed-run:
until_success: true
attempts: 3
interval: 6h
```
`until_success: true` alows to stop if success state is reached. Set to `false` it triggers until `attempts` reached.
sloves https://github.com/kubernetes-sigs/prow/issues/268
=> Config to automatically Re-trigger failed periodics

cmd/checkconfig/testdata/combined.yaml, cmd/deck/template/spyglass.html, pkg/spyglass/lenses/buildlog/lens.go, pkg/spyglass/lenses/buildlog/lens_test.go
Reverts kubernetes-sigs/prow#296
PR is a likely culprit of https://github.com/kubernetes-sigs/prow/issues/369 so let's revert to unbreak folks until we have a chance to figure out the fix.
=> Revert "(spyglass/lenses) allow configuration sandbox permissions"

pkg/plugins/verify-owners/verify-owners_test.go, pkg/repoowners/repoowners.go, pkg/repoowners/repoowners_test.go
For this [issue](https://github.com/kubernetes-sigs/prow/issues/360). Modifies repoowners.go to handle cases where the file has an alias group but does not have any user name listed in it. 
There are multiple acceptable yamls that are being not parsed explictly and edge cases not handled. Examples are -
```
aliases:
alias-group:
```
```
aliases:
alias-group: {}
```
```
aliases:
alias-group: {alias1, alias2}
```
```
aliases:
alias-group: ""
```
All of these are valid yamls, that can cause silent failures like the one mentioned in #360 .
Fixes #360
=> Handle empty alias group case

test/integration/test/sinker_test.go
There is a flake in the `Sinker` integration test that looks like the following:
```
=== FAIL: test/integration/test TestDeletePod/running-pod (60.04s)
sinker_test.go:246: Creating client for cluster: kind-kind-prow-integration
sinker_test.go:263: Creating prowjob: running-pod-67fbb1f581d3c62bfffda7cdd410491a
sinker_test.go:267: Finished creating prowjob: running-pod-67fbb1f581d3c62bfffda7cdd410491a
sinker_test.go:271: Creating pod: running-pod-67fbb1f581d3c62bfffda7cdd410491a
sinker_test.go:275: Finished creating pod: running-pod-67fbb1f581d3c62bfffda7cdd410491a
sinker_test.go:286: Wait for sinker deleting pod or timeout in 1 minute: running-pod-67fbb1f581d3c62bfffda7cdd410491a
sinker_test.go:306: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline …
```
=> Fix `sinker's` flaky integration test

test/integration/test/sinker_test.go
Follows up on https://github.com/kubernetes-sigs/prow/pull/383 to not shadow the `err` var so that the test will properly fail when it should
=> fix error shadowing in `sinker` integration test

test/integration/test/sinker_test.go
Follows up on: https://github.com/kubernetes-sigs/prow/pull/385 as it seems the integration test is still failing with a `wait` error.
The polling logic lead to flaky results due to potential race conditions. Simply waiting 1 minute to check should only introduce a slight delay (at most) to the overall process because these tests are already run in parallel.
Fixes: https://github.com/kubernetes-sigs/prow/issues/309
=> `sinker` integration test: always wait 1 minute to check for pod deletion

pkg/plugins/approve/approve.go, pkg/plugins/approve/approve_test.go, pkg/plugins/approve/approvers/approvers_test.go
Fixes #175
It seems that we were simply adding the author as an assignee when opts.HasSelfApproval()  (returns true if require_self_approval is false) was false. But we should not assign the author when require_self_approve is true. (i.e. when opts.HasSelfApproval() returns false).
Additionally, added test cases to cover for some unvcovered cases - when assignee and suggested approvers, both are needed. 
Also, removed a test case which didn't make any sense, it said do not suggest  to /assign already assigned "cjwagner" but "cjwagner" being the author should not be assigned when selfApprove is false (i.e. require_self_approval is true).
=> Do not suggest author when require_self_approve is true.

pkg/github/client.go, pkg/github/client_test.go
Github workflows consisting of multiple workflows do not show up as "failed" in all cases. Sometimes they are instead "cancelled". Additionally, the "status" query parameter is overloaded and includes both the "status" and "conclusion" field from the response. This makes it hard to use and reason about. On the other hand, there is now a query parameter for the head_sha, that we have so far been handling manually.
This commit changes GetFailedActionRunsByHeadBranch to make use of the head_sha parameter and removes the query for "status==failed". Instead, the returned runs are checked for any that have status == completed and conclusion != success.
A unit test is also added.
Fixes: #417
=> Support retriggering complex workflows

cmd/deck/static/common/common.ts, cmd/deck/static/prow/prow.ts, cmd/deck/static/style.css, cmd/deck/template/base.html, cmd/deck/template/index.html, cmd/deck/template/tide-history.html, cmd/deck/template/tide.html
What do you thing about adding the "default" material style for tables - used on https://prow.k8s.io/command-help - for other tables as well?
This let the appearance more appealing and modern and also give a visual feedback on what line we are with the mouse - very helpful.
This also shrink the font to 13px against the original 16px, I modified it to 15px.
Also, changed the `Job YML` title to `YAML` so the cell doesn't break.
A demo can be viewed [here](https://deck-material.apps.ci.l2s4.p1.openshiftapps.com/) but will be disabled sooner or later.
As a reference for the future, this is the version without style:
This is the version with style and line feedback:
=> Using material design for other tables as well

config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml, pkg/apis/prowjobs/v1/types.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/prow-config-documented.yaml, pkg/plank/controller_test.go, pkg/plank/reconciler.go
Consolidates the revival logic in `pkg/plank/reconciler.go` and limits the number of times we "revive" to 3 before we fail the prowjob.
Revival happens in case the pod is in an unknown, evicted or unreachable state.
**Future work:** in a follow-up PR, I'll add support for handling pods that are in a terminated state (the node on which the pod was running was shut-down).
REVIEWER NOTE: "revival" might not be a good term, feel free to suggest a different name
=> Consolidate revival logic in case pod is in an unknown, evicted or unreachable state, limit the number of revivals to 3

pkg/statusreconciler/controller.go
This pull request updates the behavior of the `triggerNewPresubmits` function in the `pkg/statusreconciler/controller.go` file to improve how presubmit jobs are triggered when their `run_if_changed` regular expression is modified.
* Updated the logic in the `triggerNewPresubmits` function to ensure that when a presubmit job's `run_if_changed` regexp changes, PRs are checked against the new regexp. The job is triggered only if the new regexp matches, instead of forcing the job to run on all PRs. This changes the default behavior of the filter to `false`. (`[pkg/statusreconciler/controller.goL245-R247](diffhunk://#diff-de6ed3d581802eb6dd00b4d1f031d4e9e9dfc5bbcf25f75c6f87da4b141c148dL245-R247)`)
=> chore(pkg/statusreconciler): update code comment on presubmit filter behavior

pkg/flagutil/jira.go
The original change incorrectly tested against default values instead of actually setting default values, properly, if the values all contained numeric nil (i.e. 0) values.  This PR will set reasonable default values always and users can override them as needed.
=> Properly set defaults for jira rate limiting

pkg/github/client.go, pkg/github/client_test.go
This pull request updates the logic for filtering GitHub workflow runs and includes a minor import addition to support the changes. The primary goal is to refine the selection criteria for completed jobs by excluding both "skipped" and "successful" runs.
* Updated the filtering condition in `GetFailedActionRunsByHeadBranch` to exclude runs with the conclusion "skipped" in addition to "success". This ensures that skipped workflows are no longer considered as failed runs. (`pkg/github/client.go`, [pkg/github/client.goR2082-R2086](diffhunk://#diff-2bb9ccd2fcbbcfd99cb8e400704ea77cc80dbf62f5982b1f6ed1a0966ac42ae5R2082-R2086))
* Added the `slices` package to the import list to leverage its utility functions, specifically `slices.Contains`, for cleaner and more readable filtering logic. …
=> fix(pkg/github): skip skipped workflow runs when collecting failed runs

cmd/checkconfig/main.go, cmd/checkconfig/main_test.go
IDE showed me an unused parameter which looked weird. The plugin path was validated twice, probably as a copy-paste artifact.
=> checkconfig: fix checking separate config hierarchies

pkg/plugins/trigger/generic-comment.go
Emit a message similar to the welcome message in case of untrusted user and trigger.IgnoreOkToTest.
See https://github.com/kubevirt/kubevirt/pull/14110#issuecomment-2781210119
=> fix(generic comment): avoid ok-to-test message on IgnoreOkToTest

pkg/plugins/hold/hold.go, pkg/plugins/hold/hold_test.go
Since commit 69ffdfc, the `/hold` command allows a reason. For example:
```
/hold while we wait for foo to merge
```
However, you can't do the equivalent for `/unhold` and its variants. This is confusing. Correct it. This opens up the chance that someone could do e.g.
```
/hold cancel everything while I review this epic code
```
And get an unhold rather than a hold, but that seems an acceptable risk.
=> Allow reason with /unhold too

config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml, pkg/apis/prowjobs/v1/types.go, pkg/apis/prowjobs/v1/zz_generated.deepcopy.go, pkg/config/prow-config-documented.yaml, pkg/secretutil/censor.go, pkg/secretutil/censor_test.go, pkg/sidecar/censor.go, pkg/sidecar/options.go, pkg/spyglass/lenses/common/bindata.go
Short "secrets" tend not to be so, and cause issues when it gets censored in test names or serializable fields like test duration.
An example, putting 443 in a secret would cause that to be censored from junit durations, rendering the XML unmarshallable.
Or, using "mon", for montreal - a location of a data center - will cause test names that mention `monitoring` to become `XXXitoring`.
These are real-world examples in OpenShift.  It's unlikely any truly secret data is less than 6 characters, but to be safe the behavior is unchanged upstream -- the default minimum length is 0.
fixes [#26453](https://github.com/kubernetes/test-infra/issues/26453)
=> secretutil: implement configurable minimum secret length

cmd/admission/dev.yaml, cmd/branchprotector/oneshot-job.yaml, cmd/generic-autobumper/imagebumper/imagebumper_test.go, cmd/peribolos/dev.yaml, cmd/pipeline/dev.yaml, site/content/en/docs/components/cli-tools/generic-autobumper.md
/kind cleanup
/sig testing
Legacy image registry removal purpose
[Migrate away from gcr.io/k8s-testimages repo #470](https://github.com/kubernetes-sigs/prow/issues/470)
NONE
NONE
NONE
=> ci: remove legacy gcr.io/k8s-testimages image registry

pkg/plugins/verify-owners/verify-owners.go, pkg/plugins/verify-owners/verify-owners_test.go, pkg/repoowners/repoowners.go, pkg/repoowners/repoowners_test.go
Fixes #360
Handle cases as discussed in the issue. Add a PR comment for cases where aliases are empty instead of throwing errors. This is because lot of existing users have empty aliases and their approvals were broken.
=> PR comment for empty aliases, handle other cases.

pkg/git/v2/executor.go, pkg/git/v2/executor_test.go, pkg/git/v2/publisher.go
This commit addresses a security vulnerability where GitHub tokens were being exposed in logs when executing git commands. The issue occurred in two places:
1. In executor.go, command arguments containing credentials were being logged without censoring sensitive information
2. In publisher.go, remote URLs with embedded tokens were being logged directly
This fix ensures that sensitive information like GitHub tokens is not exposed in logs, improving the security posture of the application.
=> fix: prevent GitHub token leakage in git command logs

cmd/ghproxy/ghproxy.go, pkg/ghcache/ghcache.go
add ghproxy support to valkey/redis using ACL (username and password)
when using `--redis-address` the user can pass the username and password if the redis server has auth
New parameters:
`--redis-username=username`
`--redis-password=password`
=> feat: add ghproxy valkey/redis ACL support

site/content/en/docs/getting-started-deploy.md
According to https://github.com/kubernetes/test-infra/blob/1faa9de05541d29656d832b997997c688c273d58/config/prow/cluster/starter/starter-gcs.yaml#L971C10-L971C33 , the label should be `app=prow-controller-manager` ( rather than `app=plank` ).
=> Fix cmd that retrieve the version of plank
