site/.rgignore

Ignore third-party dependencies and generated files/folders.

add .rgignore file

---

site/Makefile
site/assets/scss/_styles_project.scss
site/config.toml
site/content/en/docs/Overview/architecture.md
site/package-lock.json

This also enables mermaidjs (which comes bundled with the Docsy theme that we use). While we're at it, we also update the Docsy theme itself.
/cc @mpherman2

add architecture diagram

---

site/content/en/docs/Metrics/_index.md

Signed-off-by: Ankit152 <ankitkurmi152@gmail.com>
Added fix to the Metrics page.

Fixed metrics page deployment

---

site/content/en/docs/Legacy Snapshot/prow/inrepoconfig.md
site/content/en/docs/Legacy Snapshot/prow/metadata_artifacts.md
site/content/en/docs/Legacy Snapshot/prow/spyglass/write-a-lens.md

Minor grammatical fix removing some duplicated words

grammar: remove duplicate words

---

site/content/en/docs/components/core/tide/maintainers.md

Requested in https://kubernetes.slack.com/archives/C7J9RP96G/p1671494352250439
/assign @listx 
/cc @BenTheElder

Start a tide troubleshooting guide with details about a GH search indexing bug and mitigation.

---

site/content/en/docs/inrepoconfig.md

Not really sure how best to keep this evergreen but at least this matches what's in the sample kubernetes configs today

Update version of checkconfig in sample

---

site/content/en/docs/spyglass/_index.md

Wasn't sure how this sentence was meant to end so I just put something in here that seems reasonable

Finish incomplete lenses description

---

site/content/en/docs/jobs.md

I was a bit confused by this, so hopefully this helps others.  Assuming my interpretation is correct, that is!

Try to clarify the postsubmit / presubmit distinction a bit

---

site/content/en/docs/jobs.md

Document the changes from https://github.com/kubernetes/test-infra/pull/29309

Update docs for new PULL_HEAD_REF env var

---

site/content/en/docs/announcements.md

Announce the work done for kubernetes/test-infra/issues/26590.

Update announcements.md for blobless cloning

---

site/content/en/docs/getting-started-deploy.md

Update documentation to reflect changes in https://github.com/kubernetes/test-infra/pull/29935
Work in progress. Do not merge unless ^ has been merged.

Update Deploying Prow page to reflect placeholder change

---

site/content/en/docs/overview/_index.md

Add gardener prow instance to the list of prow instances in the wild :) 
cc @oliver-goetz

Add gardener prow instance to list

---

site/content/en/docs/jobs.md

Document the changes from https://github.com/kubernetes/test-infra/pull/30738

Update docs for new PULL_TITLE env var

---

site/content/en/docs/announcements.md
site/content/en/docs/inrepoconfig.md

Also add a blurb about symlinks not being supported in the dedicated page for inrepconfigs.
/cc @airbornepony @cjwagner @timwangmusic

announce inrepoconfig handling backward-incompatibility

---

OWNERS

Add timwangmusic to the approvers list in OWNERS file.

Add timwangmusic as approver

---

OWNERS

This is to kick-off the discussion, as suggested by @stevekuznetsov in https://github.com/kubernetes-sigs/prow/issues/68#issuecomment-1811270389

Self nominating matthyx as approver

---

site/content/en/docs/components/optional/sub.md

The main thing this fixes is the incorrect example for the PubsubMessage type. See individual commits for the changes.
/cc @cjwagner

fixes for sub

---

site/content/en/docs/components/core/tide/config.md

- Try to clarify the from-branch-protection and skip-unknown-contexts options a bit more
- Add undocumented required-if-present-contexts option

Improve tide config docs

---

.golangci.yml
.ko.yaml
Makefile
hack/make-rules/go-run/arbitrary.sh
hack/make-rules/update/codegen.sh
hack/make-rules/update/file-perms.sh
hack/make-rules/update/go-deps.sh
hack/make-rules/update/gofmt.sh
hack/make-rules/update/misspell.sh
hack/make-rules/update/ts-rollup.sh
hack/make-rules/verify/all.sh
hack/make-rules/verify/boilerplate.sh
hack/make-rules/verify/file-perms.sh
hack/make-rules/verify/go-deps.sh
hack/make-rules/verify/gofmt.sh
hack/make-rules/verify/golangci-lint.sh
hack/make-rules/verify/misspell.sh
hack/make-rules/verify/yamllint.sh

Add assorted files from kubernetes/test-infra that are needed to build and test.

---

hack/scripts/sync-prow.sh

I've tested this and it seems to be working properly now.

Update sync-prow.sh script to sync all needed code and handle the module rename.

---

.ko.yaml

Remove robots/issue-creator and testgrid/cmd/configurator from .ko.yaml.

Remove non-prow images in .ko.yaml file.

---

OWNERS

/cc @stevekuznetsov @petr-muller @cjwagner 
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

add droslean in the OWNERS file

---

OWNERS
cmd/sub/OWNERS
pkg/pubsub/OWNERS
test/integration/OWNERS

I will be changing my $DAYJOB and won't be working on this project directly any more.

OWNERS: move listx to emeritus status

---

pkg/github/report/report_test.go
pkg/plugins/bugzilla/bugzilla_test.go
pkg/plugins/dco/dco_test.go
pkg/plugins/invalidcommitmsg/invalidcommitmsg_test.go
pkg/plugins/respond.go
pkg/plugins/retitle/retitle_test.go

chore: replace issue link to kubernetes-sigs/prow repo

---

pkg/plugins/assign/assign.go

_This PR is following up to #164_ 
-  Write PluginHelp in assign.go

Doc: Write PluginHelp in assign.go

---

go.mod
hack/tools/go.mod
site/go.mod

-  Update Go version from 1.21 to 1.22

nit: Update Go version

---

cmd/external-plugins/cherrypicker/server.go

cherrypicker: create comment for failed patch requests

---

site/config.toml
test/integration/config/prow/cluster/crier_rbac.yaml
test/integration/config/prow/cluster/deck_deployment.yaml
test/integration/config/prow/cluster/deck_service.yaml
test/integration/config/prow/cluster/deck_tenant_deployment.yaml
test/integration/config/prow/cluster/hook_deployment.yaml
test/integration/config/prow/cluster/hook_service.yaml
test/integration/config/prow/cluster/horologium_deployment.yaml
test/integration/config/prow/cluster/prow_controller_manager_deployment.yaml
test/integration/config/prow/cluster/prow_controller_manager_rbac.yaml
test/integration/config/prow/cluster/prow_controller_manager_service.yaml
test/integration/config/prow/cluster/sinker_service.yaml
test/integration/config/prow/cluster/tide_deployment.yaml
test/integration/config/prow/cluster/tide_service.yaml
test/integration/config/prow/cluster/webhook_server_deployment.yaml
test/integration/config/prow/cluster/webhook_server_service.yaml

This PR adds a missing period after 'The K8s Authors' string, in the copyright strings.

nit: Add a missing period after 'The K8s Authors' string, in copyright strings

---

pkg/github/client.go
pkg/github/types.go

This change adds the ListTags method into the client.

GitHub: Add ListTags method

---

pkg/gangway/gangway.go
test/integration/test/gangway_test.go

Periodics do not have refs, this caused panics.

gangway: add nil check on refs

---

pkg/pjutil/trigger.go

Sometimes you only want to wait for pending states

Allow Trigger To Watch Any State - pjutil

---

site/content/en/docs/getting-started-deploy.md

This PR makes minor updates listed below to help others deploying Prow.
* Move Commit statuses in repo permissions bullet list to order permissions alphabetically
* Add a heading for prow namespace creation as some of the steps require namespace to exist
* Add link to Prow CRD

doc: Minor updates to getting started doc

---

OWNERS

Trying to catch up with upstream changes and can share some review loads :-)

Add krzyzacy to Prow approvers

---

pkg/plugins/config.go
pkg/plugins/config_test.go

Excluded repos are still validated for duplicate plugin configuration against their org. This prevents the possibility to exclude a repo from an org's plugin configuration, and then select some of the plugins that the org has enabled in the repo's configuration.
Discovered this issue from trying to use the `excluded_repos` configuration after abandoning the functionality in https://github.com/kubernetes-sigs/prow/pull/273.

fix `validatePluginsDupes` to account for `excluded_repos`

---

pkg/gangway/gangway.go
test/integration/test/gangway_test.go

This PR actually implements the yet unimplemented but defined `ListJobExecutions` method for gangway.
As I didn't find any specific documentation about how it should behave with regards to authentication, I chose to do as for the `GetJobExecution` and not enforce the `allowed_jobs_filters` for a RO operation.

gangway: Add ListJobExecutions implementation

---

pkg/flagutil/kubernetes_cluster_clients.go

Setting up a new cache will apply default values. If multiple clients share the same options, ultimately the `client.New()` call would race to setup the namespace cache options.
The issue was introduced with a recent controller-runtime update in Prow.
Fixes #288

fix race condition when loading multiple cluster contexts

---

cmd/deck/main.go

This is a follow up to the failed attempt from https://github.com/kubernetes-sigs/prow/pull/308. It makes it more clear that the CSRF logic wraps the server, and starts the readiness endpoint immediately before starting the server.

`deck`: move readiness serve to where we actually start the server

---

pkg/pjutil/help.go
pkg/plugins/trigger/generic-comment_test.go

Fixes #321
Signed-off-by: wuhuizuo <wuhuizuo@126.com>

trigger: improve experience of guided comment

---

pkg/deck/jobs/jobs.go
pkg/deck/jobs/jobs_test.go

In OpenShift's prow installation, we give many jobs a tenant id of `gangway` in order to facilitate triggering them via gangway. Due to this, we must include the `gangway` tenant id in our `deck` instance in order for these jobs to show.
This results in deck listing the `hidden` jobs because of this logic: https://github.com/kubernetes-sigs/prow/blob/db89760fea406dd2813e331c3d52b53b5bcbd140/pkg/deck/jobs/jobs.go#L145-L149
That isn't so bad, and does not have a simple solution.
However, we recently discovered that the `/log` endpoint (which is accessible via a button beside the listing) actually shows the logs. This PR fixes that part so we don't leak sensitive data.
Note: I tested this out by using a locally built image, and it functions as desired in the standard, and "hidden" `deck` …

`deck`: "/log" endpoint should not show `hidden` jobs if deck isn't configured to allow `hidden`

---

pkg/statusreconciler/controller.go
pkg/statusreconciler/controller_test.go

fix(status-reconciler): correctly run run_if_changed presubmits

---

pkg/plugins/config.go

Little cleanup from prior pull request 
See https://github.com/kubernetes-sigs/prow/pull/349#discussion_r2002113516

Fix WaitForStatus comment to use the correct field name

---

pkg/flagutil/jira.go
pkg/jira/jira.go

This PR adds the ability to specify a custom backoff function into the Jira Client's underlying retryablehttp client.  This provides a convenient way to allow consumers to specify their own Backoff logic if/when the `DefaultBackoff` ([here](https://github.com/hashicorp/go-retryablehttp/blob/390c1d807b1dfda09c64e992bdd5e58a00daa698/client.go#L551-L566)) is not sufficient.

Adding the ability to specify a custom backoff

---

pkg/jira/jira.go

This PR fixes the default values if/when the nil values of the parameters are used.  :man_facepalming:

Properly set default values

---

pkg/config/config.go
pkg/config/jobs.go
pkg/config/jobs_test.go
pkg/config/zz_generated.deepcopy.go

We started to use tolerations more often using in prow. eg https://github.com/kubernetes/test-infra/pull/34817
I want to set this using presets.

set tolerations using presets

---

site/OWNERS

Needs https://github.com/kubernetes/test-infra/pull/35084 first

site: add an OWNERS file to apply area/documentation label

---

pkg/crier/reporters/gcs/kubernetes/reporter.go
pkg/crier/reporters/gcs/kubernetes/reporter_test.go

We regularly encounter prow jobs that fail due to kernel/os regressions. To make these easier to debug, Prow will now dump the node object that the pod runs on. We will also deploy NFD on our build clusters, making the OS and kernel versions available for contributors to view without requiring knowledge of the clusters.

dump node info in the podinfo.json file
